name: build

on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        target:
          - windows
          - macos
        include:
          - target: windows
            os: windows-latest
          - target: macos
            os: macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install pyinstaller
      - run: pip install -r requirements.txt
      - if: matrix.target == 'macos'
        run: brew install python-tk

      - run: pyinstaller main.py --name gl2f-tbl --onefile --noconsole

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: dist/gl2f-tbl.*

  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: windows
      - run: zip windows.zip windows/*

      - uses: actions/download-artifact@v4
        with:
          name: macos
      - run: zip -r macos.zip macos/*

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_note: true
          files: |
            windows.zip
            macos.zip
